download: null
names:
  0: tree
  1: crown
  2: olive
test:
- /raid/giustinomiglionico/datasets/ROUND_2/test
train:
- /raid/giustinomiglionico/datasets/ROUND_2/train
val:
- /raid/giustinomiglionico/datasets/ROUND_2/val
