download: null
names:
  0: tree
  1: crown
  2: olive
test:
- /home/GaetanoFrancesco/c-v_rounds/ROUND_2/test
train:
- /home/GaetanoFrancesco/c-v_rounds/ROUND_2/train
val:
- /home/GaetanoFrancesco/c-v_rounds/ROUND_2/val