download: null
names:
  0: tree
  1: crown
  2: olive
test:
- /raid/giustinomiglionico/datasets/ROUND_1/test
train:
- /raid/giustinomiglionico/datasets/ROUND_1/train
val:
- /raid/giustinomiglionico/datasets/ROUND_1/val
