download: null
names:
  0: tree
  1: crown
  2: olive
test:
- /raid/giustinomiglionico/datasets/ROUND_0/test
train:
- /raid/giustinomiglionico/datasets/ROUND_0/train
val:
- /raid/giustinomiglionico/datasets/ROUND_0/val